# syntax=docker/dockerfile:experimental

ARG font="code7"
FROM ubuntu AS fontforge
ARG font="code7"
ENV font=${font}
RUN yes | unminimize
RUN DEBIAN_FRONTEND=noninteractive apt-get install -yq --force-yes python3-pip python3-fontforge
RUN yes | pip3 install bdf2ttf

